name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::820394158530:role/github-actions-widdix-hello
          role-session-name: github-actions
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push images to ECR
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t public.ecr.aws/l0j0k6k8/hello:latest -f docker/Dockerfile_latest --load .
          docker buildx build --platform linux/amd64,linux/arm64 -t public.ecr.aws/l0j0k6k8/hello:v1 -f docker/Dockerfile_v1 --load .
          docker buildx build --platform linux/amd64,linux/arm64 -t public.ecr.aws/l0j0k6k8/hello:v2 -f docker/Dockerfile_v2 --load .
          docker push public.ecr.aws/l0j0k6k8/hello:latest
          docker push public.ecr.aws/l0j0k6k8/hello:v1
          docker push public.ecr.aws/l0j0k6k8/hello:v2
